### ISSUE TITLE
Job for mariadb.service failed because the control process exited with error code.

### ISSUE THREAD

**Issue by tsull360** [itiligent/Guacamole-Install#8] opened 2023-07-10 02:56 UTC
Hello,
Working with the script on Debian 12, getting the subject error. Didn't see any history on this, thought I would raise it as an issue.

![image](https://github.com/itiligent/Guacamole-Setup/assets/19385205/ae78856f-3afd-4b7e-9d77-8bd41be2a03d)

**Comment by itiligent** [comment] 2023-07-10 14:25
Hi and thanks for the feedback... Yes, it seems Debian 12 breaks a bunch of things.. :( 

I ran up a vanilla Debian 12 and it seems theres a few new and screwy things that might have changed around various OS behvaviour, db defaults, root permissions, unix socket access and such ... but Im not fully sure of the exact cause as yet.  I can replicate a range of errors around database creation where db root access is needed (parts that have worked perfectly for years) and there is an earlier mysql timezone fix that now breaks mariadb cold. 

As I'm a but time limited it would seem prundent to hold back from and wait for the dust to settle with such a new OS version and to absorb a bit more backgounf info on whats changed.  Best to stay closer to Bullseye / 11 variants for the time being. 

I'll leave this open with intent to take a closer look when I can find time... or if some other kind soul wants to help and submit PR that would be awsome!

**Comment by itiligent** [comment] 2023-07-10 17:00
Tim,

An update:

Just now I was able to massage the code through in smaller chunks and I could successfully create the guacamole database. This might be a Maria bug coz no other versions have had any issue with this exact script syntax in years, unless I’m missing something really dumb...

To reproduce the error, run these commands in a script running as sudo :
`SQLCODE=blah blah sql setup commands…
echo ${SQLCODE} | mysql -u root -D mysql -h ${MYSQL_HOST} -P ${MYSQL_PORT}`

will return `ERROR 1698 (28000): Access denied for user 'root'@'localhost'`

The error is a bit misleading because if I omit the port number in the script commands, auth works fine and the SQL code runs perfectly :

`echo ${SQLCODE} | mysql -u root -D mysql -h ${MYSQL_HOST}`

Weird

**Comment by itiligent** [comment] 2023-08-03 02:06
closing this and adding a new issue relevant to debian 12

**Closed** 2023-08-03 02:06 UTC

**Comment by itiligent** [comment] 2023-08-03 02:21
closed this, replaced with a more specific issue #10
