### ISSUE TITLE
undefined reference to timer error on Guac installation 1.5.4

### ISSUE THREAD

**Issue by muzanxdem** [itiligent/Guacamole-Install#31] opened 2024-02-17 15:08 UTC
Hi,

I install the guacamole server using automatically installation provided. But when at the step of guacamole server installation, the installation was failed.

```
Installing Guacamole-Server...
Failed. See /home/debian/guac-setup/guacamole_install.log
2-install-guacamole.sh FAILED. See /home/debian/guac-setup/guacamole_install.log
```

I attach the log below as reference:

```
Making install in src/guacd
make[1]: Entering directory '/home/debian/guac-setup/guacamole-server-1.5.4/src/guacd'
  CCLD     guacd
/usr/bin/ld: /home/debian/guac-setup/guacamole-server-1.5.4/src/libguac/.libs/libguac.so: undefined reference to `timer_delete'
/usr/bin/ld: /home/debian/guac-setup/guacamole-server-1.5.4/src/libguac/.libs/libguac.so: undefined reference to `timer_settime'
/usr/bin/ld: /home/debian/guac-setup/guacamole-server-1.5.4/src/libguac/.libs/libguac.so: undefined reference to `timer_create'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:563: guacd] Error 1
make[1]: Leaving directory '/home/debian/guac-setup/guacamole-server-1.5.4/src/guacd'
make: *** [Makefile:544: install-recursive] Error 1
```

Anybody have same issue?

Thank you.

**Comment by Almighty55** [comment] 2024-02-17 15:26
yes this is a fault of subsequent guac scripts, add this before running the install script and you should be good

`export LDFLAGS="-lrt"`


It was marked as resolved, but still persists...
https://issues.apache.org/jira/browse/GUACAMOLE-1892?jql=text%20~%20%22undefined%20reference%20to%20%60timer_delete%27%22

**Comment by CloudByteSolutions** [comment] 2024-02-17 15:27
yes this is a fault of subsequent guac scripts, add this before running the install script and you should be good

export LDFLAGS="-lrt"

It was marked as resolved, but still persists...
https://issues.apache.org/jira/browse/GUACAMOLE-1892?jql=text%20~%20%22undefined%20reference%20to%20%60timer_delete%27%22

**Comment by muzanxdem** [comment] 2024-02-17 15:59
Thanks for your solution. It works!!!

**Comment by itiligent** [comment] 2024-02-17 21:53
Thanks all for the input. 

I'm hesistant to to add a test in the script to fix this when it's still a fresh guac bug and tracking every linux version variance is not a rabbit hole I want ot go down.  I'll maybe revisit if its still present after 1.5.4
 
In the meantime I've updated the issue title to make it easier to search on for those who might bump into this down the road.

**Comment by peterge-misoft** [comment] 2024-03-08 11:30
I am facing the same undefined reference error, but exporting LDFLAGS doesnt work for me :(

```
Guacamole 1.5.4 Auto Installer.
              Powered by Itiligent


Beginning Guacamole setup...

Synchronising the install script suite with the selected installation options...
OK

Updating base Linux OS...
OK     

Installing dependencies required for building Guacamole, this might take a few minutes...
OK     

Installing Postfix MTA for backup email notifications and alerts, see separate SMTP relay configuration script...
OK     

Downloading Guacamole source files...
guacamole-server-1.5.4.tar.gz   100%[=====================================================>]   1,07M  --.-KB/s    in 0,02s   
Downloaded guacamole-server-1.5.4.tar.gz
guacamole-1.5.4.war             100%[=====================================================>]  13,10M  --.-KB/s    in 0,1s    
Downloaded guacamole-1.5.4.war
mysql-connector-j-8.2.0.tar.gz  100%[=====================================================>]   4,05M  --.-KB/s    in 0,06s   
Downloaded mysql-connector-j-8.2.0.tar.gz
guacamole-auth-jdbc-1.5.4.tar.g 100%[=====================================================>]  31,44M   108MB/s    in 0,3s    
Downloaded guacamole-auth-jdbc-1.5.4.tar.gz
Source download complete.

Compiling Guacamole-Server from source with with GCC 10.2.1, this might take a few minutes...
OK     

Running make and building the Guacamole-Server application...
OK     

Installing Guacamole-Server...
Failed. See /home/guacamole/guac-setup/guacamole_install.log
2-install-guacamole.sh FAILED. See /home/guacamole/guac-setup/guacamole_install.log
guacamole@miprdguacamole:~$ env
[...]
LDFLAGS=-lrt
[...]
guacamole@miprdguacamole:~$ echo $LDFLAGS 
-lrt
guacamole@miprdguacamole:~$ tail /home/guacamole/guac-setup/guacamole_install.log
Making install in src/guacd
make[1]: Entering directory '/home/guacamole/guac-setup/guacamole-server-1.5.4/src/guacd'
  CCLD     guacd
/usr/bin/ld: /home/guacamole/guac-setup/guacamole-server-1.5.4/src/libguac/.libs/libguac.so: undefined reference to `timer_delete'
/usr/bin/ld: /home/guacamole/guac-setup/guacamole-server-1.5.4/src/libguac/.libs/libguac.so: undefined reference to `timer_settime'
/usr/bin/ld: /home/guacamole/guac-setup/guacamole-server-1.5.4/src/libguac/.libs/libguac.so: undefined reference to `timer_create'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:563: guacd] Error 1
make[1]: Leaving directory '/home/guacamole/guac-setup/guacamole-server-1.5.4/src/guacd'
make: *** [Makefile:544: install-recursive] Error 1

```

**Comment by peterge-misoft** [comment] 2024-03-08 13:26
fixed it running make distclean;autoreconf -fi;./configure;make

**Comment by itiligent** [comment] 2024-03-08 14:33
> fixed it running make distclean;autoreconf -fi;./configure;make

Thanks for the contribution.  To help me out could you please submit a PR wiith your suggest fix? (and I will test further) Also, what is your distro?

**Comment by peterge-misoft** [comment] 2024-03-08 14:56
It happened on debian, but i guess all distros are affected. You dont need these for installing guacamole for the first time, but if you reinstall it you need to run make distclean and and autoreconf before running configure & make again. I guess if you just include both commands to run every time it will work for reinstalling guacamole.

I found this in this thread: https://lists.apache.org/thread/h5zql3zdov0ngh8kp9r3yppcprq5z1jf, specifically in this mail: https://lists.apache.org/thread/jqwrgo1kgshqpzhkx6p1motrorw6rcz1

**Comment by itiligent** [comment] 2024-03-09 06:23
@peterge-misoft thanks for the info.  

I CAN repliacte the install timing issue only with Guac 1.5.4 and Bullseye/Deb11 or  Focal/U20.4. Debian 12 and Ubuntu 22/33 seem ok, and the  `export LDFLAGS="-lrt"` fixes it for me. 

However I CANT replicate the other install/reinstall behaviour you mention on any Debian/Ubuntu variant so I'd need more info before I chase that down any further. (BTW the threads you reference read to me as though the `export LDFLAGS="-lrt"` is ineed the fix . A closer look shows someone first claimng it did not work, but later coming back to say they had made an error and it did actully work... So its a mystery why you needed that extra step.

Anyhoo, I've at least applied the following LDFLAGS fix to the setup and upgrade scripts on the assumption that v1.5.4 and later might carry forward this issue. Others reading this can easily adapt code this for other distros.
```
if [[ "${OS_NAME,,}" = "debian" && "${OS_CODENAME,,}" = *"bullseye"* ]] || [[ "${OS_NAME,,}" = "ubuntu" && "${OS_CODENAME,,}" = *"focal"* ]]; then
    IFS='.' read -ra guac_version_parts <<< "${GUAC_VERSION}"
    major="${guac_version_parts[0]}"
    minor="${guac_version_parts[1]}"
    patch="${guac_version_parts[2]}"
    # Apply fix only to Guacamole 1.5.4 or above
    if (( major > 1 || (major == 1 && minor > 5) || (major == 1 && minor == 5 && patch >= 4) )); then
      export LDFLAGS="-lrt"
    fi
fi
```

**Closed by itiligent** 2024-03-09 06:23 UTC

**Comment by peterge-misoft** [comment] 2024-03-11 06:39
Yes, I am trying it in an LXC with Debian 11. However, using the latest version, reinstalling does still not work on debian 11:
```
guacamole@miprdguacamole:~$ tail /home/guacamole/guac-setup/guacamole_install.log
Making install in src/guacd
make[1]: Entering directory '/home/guacamole/guac-setup/guacamole-server-1.5.4/src/guacd'
  CCLD     guacd
/usr/bin/ld: /home/guacamole/guac-setup/guacamole-server-1.5.4/src/libguac/.libs/libguac.so: undefined reference to `timer_delete'
/usr/bin/ld: /home/guacamole/guac-setup/guacamole-server-1.5.4/src/libguac/.libs/libguac.so: undefined reference to `timer_settime'
/usr/bin/ld: /home/guacamole/guac-setup/guacamole-server-1.5.4/src/libguac/.libs/libguac.so: undefined reference to `timer_create'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:563: guacd] Error 1
make[1]: Leaving directory '/home/guacamole/guac-setup/guacamole-server-1.5.4/src/guacd'
make: *** [Makefile:544: install-recursive] Error 1

guacamole@miprdguacamole:~$ ls -l
total 54
-rwxr-xr-x 1 guacamole guacamole 41995 Mär 11 07:35 1-setup.sh
```

**Comment by itiligent** [comment] 2024-03-11 07:20
Can you please clarify? It works or it does not? (your post contradicts)
 
yestday I confirmed Debian 11 indeed had this issue, and same with Ubuntu 20.4,. 

In my clean test enviromemnt (Esxi) the changes I added to the setup resolved this issue for both versions.  I was not able to replicate your other re-install issue on about 5 other versions I tried too.

**Comment by peterge-misoft** [comment] 2024-03-11 07:23
It does work on the **initial** install, but it doesnt work when **reinstalling** on Debian 11 LXC

**Comment by itiligent** [comment] 2024-03-11 07:27
ok, lets expore what you mean by reinstall, and why reinstall, and your setup. I can run both the the installer and the upgrade script over and over and over and get no issues on any version. My testing is done with a default minimim install of Debian 11, or Unbuntu server 20.4, only with apt update run. (Not pre-cooked cloud images or other images from 3rd parties.)

**Comment by peterge-misoft** [comment] 2024-03-11 07:34
Wait what do you mean with the update script?

This morning guacamole wasnt working and displayed an error on the login form. I saw some errors with failed login for root and decided to reinstall the application in complete. We are still testing the application so thats no problem. So I reran the setup 1-setup.sh script and that was when I faced the undefined reference error again (https://github.com/itiligent/Guacamole-Install/issues/31#issuecomment-1987725285).

I am using this debian 11.7.1 image available in proxmox templates:
![image](https://github.com/itiligent/Guacamole-Install/assets/162673647/de5b03ec-83d6-40c0-8992-c466982f0917)

**Comment by itiligent** [comment] 2024-03-11 09:00
In future, please note the supplied issue temple to help gather important background info and context.  

Please be aware that if I can't replicate your issue and you don't take time to provide background context or communicate troubleshooting actions already undertaken, then it is indeed quite hard to help you.   Your part must be to troubleshoot via  trying to replicate a working system, not simply saying it does not work. 

You're only course of troublshooting all along has been to first isolate all other potential issues with your current server from those that relate to just the the bug that is fixed with e export LDFLAGS="-lrt" as menaiotned  here - https://issues.apache.org/jira/browse/GUACAMOLE-1892.

So, run run up a new vanilla Debian 11 on lxc, then run apt update, then reboot then try and run the guacamole install script. Then re-run the install scripn. If that works (as it does for me) then you've stepped forward by acertaining that the issue to something specific to your system. If you replicate the same problem on a new vanilla build then there is sufrace ware to work on regarding other enviromental differences between LXC and Esxi perhaps.. 
  
ps The upgrade script in this repo is for upgrading exsisting guacamole installed to the latest version. It is based on a subset of the installer routine.

**Comment by itiligent** [comment] 2024-03-11 09:10
another thought...you could also try going to debian 12, or downgrading to guac 1.5.3 on your live system. Snapshot your system first then adjust the upgrade script to downgrade your current system. If you get the same issues on a eariler version of guac then it would seem clear its not related to the 1892 bug wich is 1.5.4 specific.

**Comment by peterge-misoft** [comment] 2024-03-11 09:14
We can use debian 12 in LXC for now because we are missing updates on our proxmox hypervisors :/

I guess we will look into remotely or meshcentral instead of guacamole...

**Comment by itiligent** [comment] 2024-03-11 09:23
what about debug mode (which I think will tell you exactly whats broken and will lead you to a fix) or guac downgrade tests? Sysadmins gotta be prepared to do some troubleooting!

**Comment by peterge-misoft** [comment] 2024-03-11 09:26
https://en.wikipedia.org/wiki/KISS_principle
